### ISSUE TITLE
Error in EspalexaBasic

### ISSUE THREAD

**Issue by educrocha** [Aircoookie/Espalexa#131]
Hi, I just download Espalexa, opened "EspalexaBasic.ino" and got "Espalexa.h:302:38: error: 'response' was not declared in this scope"

What is wrong?

**Comment by Aircoookie** [comment]
Hi, this `response` was erraneously left in version 2.4.6 of Espalexa when building for ESP32. Please make sure you have the latest 2.4.7, the issue should be fixed there :)

**Comment by educrocha** [comment]
> Hi, this `response` was erraneously left in version 2.4.6 of Espalexa when building for ESP32. Please make sure you have the latest 2.4.7, the issue should be fixed there :)

Thanks for your attention, now, compiled correctly. But still not working. My Alexa APP do not find any thing. I just put my SSID and PASSWORD, but do not work.

**Comment by Aircoookie** [comment]
Do you have a physical Echo speaker on your network? Try "Alexa, discovering devices" with that. If you only have the app or a fire tv stick, it can unfortunately not discover Espalexa.

**Comment by educrocha** [comment]
> Do you have a physical Echo speaker on your network? Try "Alexa, discovering devices" with that. If you only have the app or a fire tv stick, it can unfortunately not discover Espalexa.

No, I'm using my Alexa APP only.

**Comment by Aircoookie** [comment]
Sorry, in that case Espalexa will not work for you.
